name: PHP Composer

on:
  push:
    branches:
      - main
      - devep
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install composer
        run: composer install
